// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/postagens": {
            "post": {
                "description": "Cria uma nova postagem no sistema com os dados fornecidos no corpo da requisição",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "postagens"
                ],
                "summary": "Insere uma nova postagem",
                "parameters": [
                    {
                        "description": "Nova postagem",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/postagemsvc.PostagemWrite"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Postagem inserida com sucesso",
                        "schema": {
                            "$ref": "#/definitions/postagemhandler.PostagemResponse"
                        }
                    },
                    "400": {
                        "description": "Erro ao decodificar corpo da requisição",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro ao salvar postagem",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/postagens/{id}/detalhes": {
            "get": {
                "description": "Retorna todas as informações de uma postagem com base no ID fornecido.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "postagens"
                ],
                "summary": "Buscar detalhes da postagem",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da Postagem",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/postagemsvc.Postagem"
                        }
                    },
                    "500": {
                        "description": "Erro interno ao buscar a postagem ou ao codificar a resposta",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/postagens/{id}/imagem": {
            "post": {
                "description": "Recebe um arquivo de imagem e o UUID de uma postagem. Retorna status 202 em caso de sucesso.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "postagens"
                ],
                "summary": "Upload de imagem de postagem",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID da postagem",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Arquivo de imagem (máx 10MB)",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Status Accepted (202)"
                    },
                    "400": {
                        "description": "Erro na leitura da imagem ou ID inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro interno no upload",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/trocas": {
            "post": {
                "description": "Registra uma proposta de troca com base nos dados enviados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trocas"
                ],
                "summary": "Cadastra nova proposta",
                "parameters": [
                    {
                        "description": "Dados da proposta",
                        "name": "proposta",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/propostarepo.PropostaWriteModel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Proposta criada com sucesso e ID retornado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Body inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro ao salvar proposta",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/trocas/{id}/historico": {
            "get": {
                "description": "Retorna propostas enviadas ou recebidas por um usuário com base no tipo e status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trocas"
                ],
                "summary": "Lista propostas do usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tipo de proposta (enviadas ou recebidas)",
                        "name": "tipo",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Status da proposta (pendente, aceita, recusada)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/propostarepo.PropostaFormatada"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/trocas/{id}/imagem": {
            "post": {
                "description": "Recebe um arquivo de imagem e o UUID de uma troca. Retorna status 202 em caso de sucesso.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trocas"
                ],
                "summary": "Upload de imagem de troca",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID da troca",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Arquivo de imagem (máx 10MB)",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Status Accepted (202)"
                    },
                    "400": {
                        "description": "Erro na leitura da imagem ou ID inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro interno no upload",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/trocas/{id}/status": {
            "put": {
                "description": "Altera o status da proposta (aceita, recusada, pendente)",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "trocas"
                ],
                "summary": "Atualiza o status da proposta",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da proposta",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Novo status",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/propostahandler.StatusUpdatePayload"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Atualizado com sucesso",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/usuarios": {
            "post": {
                "description": "Insere um usuário no sistema com base nos dados fornecidos no corpo da requisição",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "usuarios"
                ],
                "summary": "Cadastra um novo usuário",
                "parameters": [
                    {
                        "description": "Dados da proposta",
                        "name": "proposta",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usuariorepo.WriteUsuario"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Usuário inserido com sucesso e ID retornado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Erro ao decodificar corpo da requisição",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Já existe um cadastro com esse e-mail",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/usuarios/{id}": {
            "get": {
                "description": "Retorna os dados de um usuário identificado pelo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "usuarios"
                ],
                "summary": "Busca um usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usuariorepo.ReadUsuario"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Usuário não encontrado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Atualiza as informações de um usuário identificado pelo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "usuarios"
                ],
                "summary": "Atualiza dados de um usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados atualizados do usuário",
                        "name": "usuario",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usuariorepo.WriteUsuario"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Erro ao decodificar corpo da requisição",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "postagemhandler.PostagemResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "postagemsvc.Postagem": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "imagens": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "titulo": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "postagemsvc.PostagemWrite": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "titulo": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "propostahandler.StatusUpdatePayload": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "propostarepo.Produto": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "imagens": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "nome": {
                    "type": "string"
                },
                "usuario": {
                    "type": "string"
                }
            }
        },
        "propostarepo.PropostaFormatada": {
            "type": "object",
            "properties": {
                "produto_postagem": {
                    "$ref": "#/definitions/propostarepo.Produto"
                },
                "produto_proposta_troca": {
                    "$ref": "#/definitions/propostarepo.Produto"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "propostarepo.PropostaWriteModel": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "dono_postagem_id": {
                    "type": "string"
                },
                "interessado_id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "postagem_id": {
                    "type": "string"
                }
            }
        },
        "usuariorepo.ReadUsuario": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "telefone": {
                    "type": "string"
                }
            }
        },
        "usuariorepo.WriteUsuario": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "senha": {
                    "type": "string"
                },
                "telefone": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
